version: '3.1'

services:

  wordpress:
    build: ./.docker/wordpress/
    restart: always
    ports:
      - 8089:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: test
      WORDPRESS_DB_NAME: test
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/lapisense

  wordpress-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    # vstm: This is required to run wordpress-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    user: xfs
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/lapisense

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

volumes:
  wordpress:
